import {
  BusinessEntity,
  BusinessRegistrationEntity,
  BusinessRegistrationStatus,
  BusinessRegistrationType,
  CommissionEntity,
  CouponEntity,
  NotificationEntity,
  OrderEntity,
  OrderItemEntity,
  OtpVerificationEntity,
  ReviewEntity,
  RiderEntity,
  ServiceEntity,
  SubscriptionEntity,
  UserEntity,
} from './washflow.entity';

export const washflowEntities = [
  UserEntity,
  BusinessEntity,
  BusinessRegistrationEntity,
  ServiceEntity,
  OrderEntity,
  OrderItemEntity,
  SubscriptionEntity,
  RiderEntity,
  CouponEntity,
  ReviewEntity,
  CommissionEntity,
  NotificationEntity,
  OtpVerificationEntity,
];

export {
  UserEntity,
  BusinessEntity,
  BusinessRegistrationEntity,
  BusinessRegistrationStatus,
  BusinessRegistrationType,
  ServiceEntity,
  OrderEntity,
  OrderItemEntity,
  SubscriptionEntity,
  RiderEntity,
  CouponEntity,
  ReviewEntity,
  CommissionEntity,
  NotificationEntity,
  OtpVerificationEntity,
} from './washflow.entity';
